### ISSUE TITLE
Mahara Feedback checkbox should be disable (greyed out) if Locked submitted page option is set to "No"

### ISSUE THREAD

**Issue by MelvRom** [MaharaProject/moodle-assignfeedback_mahara#3]
Hi Tony,

This is an improvement request. In your documentation you wrote:

"If you set the Mahara submission option to not lock pages on submission, this plugin will have no effect. (Because there will be nothing to unlock.)"

Taken from your page: https://moodle.org/plugins/view/assignfeedback_mahara

Wouldn't be better if the Mahara feedback checkbox was greyed out (disable) if a teacher decides to select "No" in the "Locked submitted page" option? I know it's something small and probably picky, but I'm pretty sure that many users will complain because they won't take the time to read your documentation concerning this specific aspect of the plugin. In my case, I was curious enough to read :). 

Thanks,

Melvin

**Comment by agwells** [comment]
Hi Melvin,

That would be an improvement. However, we're currently working on a change to the Submission plugin that will make the Feedback plugin unnecessary, so that resolves the problem in a different way. See https://github.com/MaharaProject/moodle-assignsubmission_mahara/issues/8

Cheers,
Aaron
